### ISSUE TITLE
power wiring

### ISSUE THREAD

**Issue by ihewitt** [turbulator/pudding-mqtt-tracker#1]
Apologies for adding an "issue"! I couldn't find any other way to contact you!
I'm just getting an a9g going myself and saw your li-ion and battery check/reporting logic and was curious what your wiring/circuitry was to feed that through the AD inputs (accurately, without smoke!). :)

**Comment by turbulator** [comment]
You can find HW part of the project here: https://easyeda.com/turbo-lab/pudding-mqtt-tracker

**Comment by ihewitt** [comment]
awesome! thank you!
completely missed that in my earlier googling!

**Comment by turbulator** [comment]
I have to update readme
