### ISSUE TITLE
Can't find where to change mqtt broker address 

### ISSUE THREAD

**Issue by RobologAutomation** [turbulator/pudding-mqtt-tracker#2]
Dear sir, 

Can't find mqtt broker address in ur code can you please provide detailed instructions

Thank you

**Comment by turbulator** [comment]
You can find it [here](https://github.com/turbulator/pudding-mqtt-tracker/blob/53cc6c3e349df9c8d8c79fcecd17039e04c6bb7b/app/include/secret.h#L11)
